"""Pixel Bjorn's sprite sheet.

Edit the frames here, then regenerate the TypeScript the site uses:

    python scripts/sprite.py export components/companion/sprite.ts

and, to check the art by eye (needs Pillow):

    python scripts/sprite.py preview sprite.png
"""


PALETTE = {
    "H": "#6E4B2F",  # hair
    "h": "#9A6D43",  # hair highlight
    "k": "#4A301D",  # hair dark / sideburn
    "S": "#EDBE9C",  # skin
    "s": "#CE9A78",  # skin shade
    "E": "#23232F",  # eye
    "M": "#4A2E1A",  # moustache
    "W": "#FFFFFF",  # teeth
    "B": "#AFCBEE",  # shirt
    "b": "#86A9D6",  # shirt shade
    "J": "#3B414F",  # jacket
    "j": "#2A2F3A",  # jacket shade
    "L": "#50586B",  # lapel light
    "P": "#343946",  # trousers, charcoal to match the jacket
    "p": "#282C36",  # trouser shade
    "K": "#6A4631",  # shoes, brown leather
    "O": "#4A3022",  # shoe sole
}

HEAD = [
    "......hhhH......",
    "....HHhhhhHH....",
    "...HHHHhhhHHH...",
    "...HHHHHHHHHHH..",
    "...kSSSSSSSSk...",
    "...SSHHSSHHSS...",
    "...SSESSSSESS...",
    "..sSSSSSSSSSSs..",
    "...SSMMMMMMSs...",
    "...SMMWWWWMMs...",
    "....SSSSSSSs....",
    ".....SSSSSs.....",
    "......ssss......",
]

TORSO = [
    "...JJJBBBBJJJ...",
    "..JJLJJBBJJLJJ..",
    "..JJJLJBBJLJJJ..",
    "..jJJJJbBJJJJj..",
    "..JJ.JJJJJJ.JJ..",
    "..SS.JJJJJJ.SS..",
    ".....JJJJJJ.....",
]

LEGS_STAND = [
    ".....PPPPPP.....",
    ".....Pp..pP.....",
    ".....Pp..pP.....",
    "....KKO..OKK....",
]
LEGS_STRIDE = [
    ".....PPPPPP.....",
    "....Pp....pP....",
    "...Pp......pP...",
    "..KKO......OKK..",
]
LEGS_PASS = [
    ".....PPPPPP.....",
    "......PppP......",
    "......PppP......",
    ".....KKOOKK.....",
]

def blink(rows):
    return [r.replace("E", "s") for r in rows]

def overlay(rows, pixels):
    grid = [list(r) for r in rows]
    for (x, y), ch in pixels.items():
        grid[y][x] = ch
    return ["".join(r) for r in grid]

STAND = HEAD + TORSO + LEGS_STAND
# Lower the resting arm on that side, then raise it beside the head.
ARM_DOWN = {(12, 17): ".", (13, 17): ".", (12, 18): ".", (13, 18): "."}
def sleeve(cells):
    return {c: "J" for c in cells}

# Hand swung out, away from the head.
WAVE_OUT = {**ARM_DOWN,
    **sleeve([(14, 7), (15, 7), (14, 8), (15, 8), (14, 9), (15, 9),
              (13, 10), (14, 10), (13, 11), (14, 11), (13, 12), (14, 12), (13, 13)]),
    (14, 5): "S", (15, 5): "S", (14, 6): "S", (15, 6): "S",
}
# Hand swung back in beside the head.
WAVE_IN = {**ARM_DOWN,
    **sleeve([(13, 6), (14, 6), (13, 7), (14, 7), (13, 8), (14, 8), (13, 9), (14, 9),
              (13, 10), (14, 10), (13, 11), (14, 11), (13, 12), (13, 13)]),
    (13, 4): "S", (14, 4): "S", (13, 5): "S", (14, 5): "S",
}

FRAMES = {
    "idle": HEAD + TORSO + LEGS_STAND,
    "blink": blink(HEAD) + TORSO + LEGS_STAND,
    "walkA": HEAD + TORSO + LEGS_STRIDE,
    "walkB": HEAD + TORSO + LEGS_PASS,
    "waveA": overlay(STAND, WAVE_OUT),
    "waveB": overlay(STAND, WAVE_IN),
}

def check():
    for name, rows in FRAMES.items():
        widths = {len(r) for r in rows}
        assert widths == {16}, (name, widths)
        assert len(rows) == 24, (name, len(rows))
        for r in rows:
            for ch in r:
                assert ch == "." or ch in PALETTE, (name, ch)

def render(path, scale=14, pad=18):
    from PIL import Image, ImageDraw  # only needed for previews

    check()
    names = list(FRAMES)
    w, h = 16 * scale, 24 * scale
    sheet = Image.new("RGB", (len(names) * (w + pad) + pad, h + pad * 2 + 24), "#000319")
    draw = ImageDraw.Draw(sheet)
    for i, name in enumerate(names):
        ox = pad + i * (w + pad)
        oy = pad
        for y, row in enumerate(FRAMES[name]):
            for x, ch in enumerate(row):
                if ch == ".":
                    continue
                draw.rectangle(
                    [ox + x * scale, oy + y * scale, ox + (x + 1) * scale - 1, oy + (y + 1) * scale - 1],
                    fill=PALETTE[ch],
                )
        draw.text((ox, oy + h + 6), name, fill="#BEC1DD")
    sheet.save(path)

def export(path):
    import json
    check()
    out = [
        "// Generated by scripts/sprite.py; edit the frames there, not here.",
        '// Each frame is 16 x 24. "." is transparent; every other letter is a palette key.',
        "",
        "export const SPRITE_W = 16;",
        "export const SPRITE_H = 24;",
        "",
        "export const PALETTE: Record<string, string> = " + json.dumps(PALETTE, indent=2) + ";",
        "",
        "export const FRAMES = {",
    ]
    for name, rows in FRAMES.items():
        out.append(f"  {name}: [")
        out += [f'    "{r}",' for r in rows]
        out.append("  ],")
    out += ["} as const;", "", "export type FrameName = keyof typeof FRAMES;", ""]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    import sys

    command, target = sys.argv[1], sys.argv[2]
    if command == "export":
        export(target)
    elif command == "preview":
        render(target)
    else:
        raise SystemExit("usage: sprite.py export|preview <path>")
    print("ok")
